### ISSUE TITLE
Beautiful Doom 7.1.6 breaks keys logic in Unloved mod

### ISSUE THREAD

**Issue by d0vgan** [jekyllgrim/Beautiful-Doom#53]
GZDoom 4.6.1, Beautiful Doom 7.1.6, Unloved mod ( https://www.moddb.com/games/doom/addons/unloved ).
The command line is:
```
gzdoom.exe -iwad DOOM2.WAD -file unloved.pk3 Beautiful_Doom_716.pk3
```
When you come to the door that says "This door needs either yellow or red key" and you have the yellow key, this door is not open when playing with Beautiful Doom 7.1.6.
And I believe it _was working_ with pre-7 version of Beautiful Doom!

**Comment by d0vgan** [comment]
Attaching the corresponding save file (near this door in Unloved, playing with Beautiful_Doom_716.pk3).
[save0.zip](https://github.com/jekyllgrim/Beautiful-Doom/files/6954002/save0.zip)

**Comment by jekyllgrim** [comment]
Fixed in 3dab12d04769fbefa596fbc9cc6451ee14591096. You can play the current build (see readme for instructions) or wait for a new stable release.

In the future please use the bug report template (it appears when you click New Issue > Get Started) because I'll read it faster and it'll be easier for me to follow. It's also better than attaching save files since they may not work for various reasons and don't always present a clean testing environment.

Regarding the issue, it's a problem with Unloved. The author didn't create a proper lock and instead used an ACS script that checked for "RedCard" and "YellowCard" key names directly, which naturally breaks if keys are replaced. Nevertheless, I was able to add a function that accounts for that.

**Comment by d0vgan** [comment]
Thank you!
Just for information - is it expected that the updated version of Beautiful Doom still does not allow to go through that door when an existing saved game is used? If it is expected, can a saved game's files be tuned somehow - or is it better to start everything from scratch?

**Comment by jekyllgrim** [comment]
It'll be easiest to load your save and give yourself the right keys via console (Give RedCard, give YellowCard). The update will only affect the moment you pick up the keys, not the keys already in your inventory.
